// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpe3x3nKyC4rRNHEbUSTidUpc0L1vOa6c',
    appId: '1:349888577170:web:73759619fac1e61140704b',
    messagingSenderId: '349888577170',
    projectId: 'fitsync-app-7dc42',
    authDomain: 'fitsync-app-7dc42.firebaseapp.com',
    storageBucket: 'fitsync-app-7dc42.firebasestorage.app',
    measurementId: 'G-R8W5HGJ3Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAACD1GSfhMtIm3Qk66wAj8AUqATSEhmXY',
    appId: '1:349888577170:android:1fd3c511ceb2001940704b',
    messagingSenderId: '349888577170',
    projectId: 'fitsync-app-7dc42',
    storageBucket: 'fitsync-app-7dc42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeTZY8f_E3hqeSjKYbYhVN0y8BeP2oAcM',
    appId: '1:349888577170:ios:145aa01da60955eb40704b',
    messagingSenderId: '349888577170',
    projectId: 'fitsync-app-7dc42',
    storageBucket: 'fitsync-app-7dc42.firebasestorage.app',
    iosBundleId: 'com.example.fitsyncApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeTZY8f_E3hqeSjKYbYhVN0y8BeP2oAcM',
    appId: '1:349888577170:ios:145aa01da60955eb40704b',
    messagingSenderId: '349888577170',
    projectId: 'fitsync-app-7dc42',
    storageBucket: 'fitsync-app-7dc42.firebasestorage.app',
    iosBundleId: 'com.example.fitsyncApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpe3x3nKyC4rRNHEbUSTidUpc0L1vOa6c',
    appId: '1:349888577170:web:c81155461bf17cef40704b',
    messagingSenderId: '349888577170',
    projectId: 'fitsync-app-7dc42',
    authDomain: 'fitsync-app-7dc42.firebaseapp.com',
    storageBucket: 'fitsync-app-7dc42.firebasestorage.app',
    measurementId: 'G-9QS0H8E1SE',
  );

}